version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'mongo-finance'
    environment:
      - MONGO_INITDB_DATABASE=finance
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017:27017'